jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Sensio\Bundle\HangmanBundle\Entity\Player: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        players:
            entity: { class: SensioHangmanBundle:Player, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        game:
            pattern:                    ^/
            anonymous:                  ~
            form_login:
                login_path:             /login
                check_path:             /auth
                default_target_path:    /game/
            logout:
                path:                   /logout
                target:                 /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
